from flask import Flask, render_template, request, jsonify
from datetime import datetime
import requests
import json
import re

app = Flask(__name__)

# ==============================
# CONFIG
# ==============================
OLLAMA_URL = "http://localhost:11434/api/generate"
OLLAMA_MODEL = "llama3.1:8b-instruct-q4_0"   # or codellama / llama3

reviews = []  # in-memory storage


# ==============================
# ROUTES
# ==============================
@app.route('/')
def index():
    return render_template("index.html")


@app.route('/analyze', methods=['POST'])
def analyze_pr():
    try:
        review = {
            "id": len(reviews) + 1,
            "pr_title": request.form.get("pr_title"),
            "language": request.form.get("language"),
            "description": request.form.get("description", ""),
            "author": request.form.get("author"),
            "repository": request.form.get("repository"),
            "source_branch": request.form.get("source_branch"),
            "target_branch": request.form.get("target_branch"),
            "git_diff": request.form.get("git_diff"),
            "timestamp": datetime.now().isoformat(),
            "status": "pending"
        }

        if not review["pr_title"] or not review["git_diff"]:
            return jsonify({"error": "PR title and Git diff required"}), 400

        # ===============================================
        # UNIFIED LLM-DRIVEN ANALYSIS PIPELINE
        # All review text is now generated by Ollama
        # ===============================================
        analysis = perform_llm_analysis(review)
        review["analysis"] = analysis
        review["status"] = analysis["recommendation"]

        reviews.append(review)

        return jsonify({
            "success": True,
            "review_id": review["id"],
            "analysis": analysis
        })

    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route('/reviews')
def get_reviews():
    return jsonify({"total": len(reviews), "reviews": reviews})


@app.route('/metrics')
def metrics():
    return jsonify({
        "total": len(reviews),
        "approved": sum(r["status"] == "approved" for r in reviews),
        "needs_changes": sum(r["status"] == "needs_changes" for r in reviews),
        "blocked": sum(r["status"] == "blocked" for r in reviews)
    })


# ==============================
# UNIFIED LLM-DRIVEN ANALYSIS
# ==============================
def perform_llm_analysis(review):
    """
    Single entry point for all code review analysis.
    
    The LLM now handles:
    - Security issue detection and explanation
    - Quality issue detection and explanation
    - Actionable suggestions for each issue
    - Positive notes for good practices
    - Overall summary and recommendation
    
    This replaces all hardcoded keyword matching and static rule logic.
    """
    
    git_diff = review["git_diff"]
    
    # Call Ollama with a comprehensive review prompt
    llm_response = query_ollama_for_review(git_diff, review)
    
    # Parse and validate LLM response
    if not llm_response:
        return generate_empty_review()
    
    # Extract recommendation from LLM analysis
    recommendation = determine_recommendation(llm_response)
    
    return {
        "security_issues": llm_response.get("security_issues", []),
        "quality_issues": llm_response.get("quality_issues", []),
        "positive_notes": llm_response.get("positive_notes", []),
        "summary": llm_response.get("summary", "Code review completed."),
        "recommendation": recommendation
    }

def extract_json_from_text(text):
    """
    Safely extract JSON object from LLM text output.
    Handles:
    - Single quotes vs double quotes
    - Backticks
    - Extra characters before/after JSON
    """
    if not text or "{" not in text:
        print("No JSON found in the text")
        return None
    try:
        # Find first { and last }
        start = text.index("{")
        end = text.rindex("}") + 1
        json_str = text[start:end]

        # Replace backticks with quotes
        json_str = json_str.replace("`", '"')

        # Replace single quotes with double quotes
        json_str = re.sub(r"(?<!\\)'", '"', json_str)

        # Remove trailing commas before closing brackets
        json_str = re.sub(r",\s*([\]}])", r"\1", json_str)

        return json.loads(json_str)
    except (ValueError, json.JSONDecodeError) as e:
        print(f"JSON Extraction Error: {e}")
        return None



def query_ollama_for_review(git_diff, review):
    """
    Query Ollama LLM for comprehensive code review analysis.
    
    The LLM is instructed to:
    - Analyze the git diff for security issues
    - Identify quality/maintainability problems
    - Generate specific, actionable suggestions
    - Identify positive practices demonstrated
    - Provide a concise summary
    
    All output is returned as JSON for safe parsing.
    """
    
    # Truncate git diff if too large to avoid token limit issues
    truncated_diff = git_diff[:8000] if len(git_diff) > 8000 else git_diff
    
    prompt = f"""You are an expert senior software engineer conducting a thorough code review.

Analyze the following git diff and provide a detailed JSON response.

PR METADATA:
- Title: {review.get('pr_title', 'N/A')}
- Language: {review.get('language', 'Unknown')}
- Description: {review.get('description', 'No description provided')}
- Author: {review.get('author', 'Unknown')}
- Repository: {review.get('repository', 'N/A')}

GIT DIFF:
{truncated_diff}

=============================================================================

Analyze this code for:
1. Security vulnerabilities (hardcoded secrets, injection risks, auth issues, etc.)
2. Code quality issues (maintainability, readability, performance, best practices)
3. Positive patterns that demonstrate good engineering practices
4. Specific, actionable suggestions for each issue identified

RESPOND ONLY WITH VALID JSON. No markdown, no code blocks, no explanations.
Include ONLY the JSON object, nothing else.

JSON FORMAT (strictly follow this structure):
{{
  "security_issues": [
    {{
      "severity": "high|medium|low",
      "title": "Short descriptive title of the security issue",
      "message": "Specific, detailed description of the security issue",
      "suggestion": "Exact actionable fix for this issue"
    }}
  ],
  "quality_issues": [
    {{
      "severity": "high|medium|low",
      "title": "Short descriptive title of the quality issue",
      "message": "Specific description of the quality issue",
      "suggestion": "Exact actionable improvement recommendation"
    }}
  ],
  "positive_notes": [
    "Specific positive practice observed in the code",
    "Another good pattern demonstrated"
  ],
  "summary": "2-3 sentence concise summary of the overall review",
  "has_blocking_issues": true|false
}}"""

    payload = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.3  # Lower temperature for more consistent JSON
        }
    }
    try:
        response = requests.post(OLLAMA_URL, json=payload, timeout=120)
        # ✅ Check if Ollama returned an error
        if response.status_code != 200:
            print(f"Ollama API returned status {response.status_code}: {response.text}")
            return None
        print("\n--- FULL OLLAMA RESPONSE ---\n", response.json())
        raw_output = response.json().get("response", "")
        print("\n--- RAW OUTPUT ---\n", raw_output)


        # Extract JSON safely
        parsed = extract_json_from_text(raw_output)
        if not parsed:
            print("ERROR: No valid JSON found in LLM output")
            return None

        return parsed

    except Exception as e:
        print(f"Unexpected Error in LLM Query: {e}")
        return None


def determine_recommendation(llm_response):
    """
    Determine the overall recommendation based on issue severity.
    
    Logic:
    - "blocked" if any security issues exist
    - "needs_changes" if any high-severity quality issues exist
    - "approved" otherwise
    """
    
    # Check for blocking issues flag from LLM
    if llm_response.get("has_blocking_issues"):
        return "blocked"
    
    # Check for security issues
    security_issues = llm_response.get("security_issues", [])
    if any(issue.get("severity") == "high" for issue in security_issues):
        return "blocked"
    
    # Check for high-severity quality issues
    quality_issues = llm_response.get("quality_issues", [])
    if any(issue.get("severity") == "high" for issue in quality_issues):
        return "needs_changes"
    
    return "approved"


def generate_empty_review():
    """
    Return a safe empty review structure when LLM analysis fails.
    """
    return {
        "security_issues": [],
        "quality_issues": [],
        "positive_notes": [],
        "summary": "Unable to complete analysis. Please try again.",
        "recommendation": "approved"
    }


# ==============================
# RUN
# ==============================
if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)
